set_switchbot_position:
  description: Sets curtain position with ability to set speed (default slow)
  fields:
    entity_id:
      description: Curtain to adjust
      selector:
        entity:
          domain: cover
          multiple: true
    speed:
      description: Slow (1) or fast mode (255)
      selector:
        select:
          options:
            - 1
            - 255
      default: 1
    position:
      description: 0/close <--> 100/open
      selector:
        number:
          min: 0
          max: 100
          step: 1

