set_switchbot_position:
  description: Sets cover position with ability to set speed (default slow)
  fields:
    entity_id:
      description: Entity cover to adjust
      selector:
        entity:
          domain: cover
          multiple: true
    speed:
      description: Slow or fast mode
      selector:
        select:
          options:
            - 1
            - 255
      default: 1
    position:
      description: Desired position
      selector:
        number:
          min: 0
          max: 100
          step: 1
set_switchbot_position_slow:
  description: Sets cover position with ability to set speed
  fields:
    entity_id:
      description: Entity cover to adjust
      selector:
        entity:
          domain: cover
          multiple: true
    position:
      description: Desired position
      selector:
        number:
          min: 0
          max: 100
          step: 1
  data:
    speed: 1

